//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponuda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ponude
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ponude()
        {
            this.Stavke = new HashSet<Stavke>();
        }
    
        public int PonudaID { get; set; }
        public Nullable<decimal> UkupnaCijena { get; set; }
        public Nullable<System.DateTime> DatumPonude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke> Stavke { get; set; }
    }
}
